const carData = [
  {
    id: 1,
    name: "Honda City",
    image: "https://imgd.aeplcdn.com/1920x1080/n/cw/ec/134287/city-exterior-right-front-three-quarter-78.jpeg?isig=0&q=80&q=80",
    type: "Sedan",
    seats: 5,
    pricePerDay: 2500,
    fuel: "Petrol",
    mileage: "18 kmpl",
    transmission: "Automatic",
    year: 2022,
    ac: "Yes",
    bootSpace: "506L",
    special: "Touchscreen Display, Rear Parking Camera"
  },
  {
    id: 2,
    name: "Hyundai Creta",
    image: "https://production.autoforce.com/uploads/version/profile_image/11804/comprar-limited_958f1eed79.png",
    type: "SUV",
    seats: 5,
    pricePerDay: 3200,
    fuel: "Diesel",
    mileage: "21 kmpl",
    transmission: "Manual",
    year: 2023,
    ac: "Yes",
    bootSpace: "433L",
    special: "Panoramic Sunroof, Wireless Charger"
  },
  {
    id: 3,
    name: "Maruti Swift",
    image: "https://shivamautozone.com/wp-content/uploads/2024/05/Swift-3-768x433.webp",
    type: "Hatchback",
    seats: 5,
    pricePerDay: 1800,
    fuel: "Petrol",
    mileage: "23 kmpl",
    transmission: "Manual",
    year: 2022,
    ac: "Yes",
    bootSpace: "268L",
    special: "Lightweight, Bluetooth Stereo"
  },
  {
    id: 4,
    name: "Toyota Innova Crysta",
    image: "https://chybmedia.s3.ap-south-1.amazonaws.com/models/cars/innova-crysta-9-240.jpg",
    type: "MUV",
    seats: 7,
    pricePerDay: 4000,
    fuel: "Diesel",
    mileage: "15 kmpl",
    transmission: "Automatic",
    year: 2021,
    ac: "Yes",
    bootSpace: "300L",
    special: "Family Car, Rear AC Vents"
  },
  {
    id: 5,
    name: "Tata Nexon EV",
    image: "https://imgd.aeplcdn.com/664x374/n/cw/ec/149123/nexon-ev-exterior-right-front-three-quarter-79.jpeg?isig=0&q=80",
    type: "SUV",
    seats: 5,
    pricePerDay: 3500,
    fuel: "Electric",
    mileage: "312 km/full charge",
    transmission: "Automatic",
    year: 2023,
    ac: "Yes",
    bootSpace: "350L",
    special: "Fast Charging, Eco-Friendly"
  },
  {
    id: 6,
    name: "Mahindra Thar",
    image: "https://offers.caimahindra.com/uploads/product/Thar%20Aqua%20Marine.png",
    type: "SUV",
    seats: 4,
    pricePerDay: 4500,
    fuel: "Diesel",
    mileage: "15 kmpl",
    transmission: "Manual",
    year: 2022,
    ac: "Yes",
    bootSpace: "Small",
    special: "Off-roader, Convertible Roof"
  },
  {
    id: 7,
    name: "Skoda Kushaq",
    image: "https://stimg.cardekho.com/images/car-images/large/Skoda/Kushaq/11795/1751867178441/Brilliant-Silver_bbbcb6-(1).jpg?impolicy=resize&imwidth=420",
    type: "SUV",
    seats: 5,
    pricePerDay: 3300,
    fuel: "Petrol",
    mileage: "17 kmpl",
    transmission: "Automatic",
    year: 2022,
    ac: "Yes",
    bootSpace: "385L",
    special: "Large Touchscreen, Alloy Wheels"
  },
  {
    id: 8,
    name: "Kia Seltos",
    image: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Kia/Seltos/8709/1755775088156/front-left-side-47.jpg",
    type: "SUV",
    seats: 5,
    pricePerDay: 3400,
    fuel: "Petrol",
    mileage: "16 kmpl",
    transmission: "Manual",
    year: 2021,
    ac: "Yes",
    bootSpace: "433L",
    special: "Voice Assist, Ventilated Seats"
  },
  {
    id: 9,
    name: "Maruti Alto",
    image: "https://spn-sta.spinny.com/blog/20221003125903/Spinny-Assured-Maruti-Suzuki-Alto-800.jpg",
    type: "Hatchback",
    seats: 5,
    pricePerDay: 1500,
    fuel: "Petrol",
    mileage: "22 kmpl",
    transmission: "Manual",
    year: 2021,
    ac: "Yes",
    bootSpace: "177L",
    special: "Very Economical, Compact"
  }
];

export default carData;
